package nl.roosterandroid.app

import kotlinx.serialization.Serializable
import java.time.DayOfWeek
import java.time.LocalDate
import java.time.LocalTime
import java.util.UUID

@Serializable
enum class EmployeeRole { MANAGER, RM, TRAINEE, BORROWED, HOST }

@Serializable
enum class ShiftKind { SETUP, DAY, MIDDLE, CLOSE, KPI, CUSTOM }

@Serializable
enum class AbsenceType {
    VACATION, SNIPPER_DAY, LEAVE, SPECIAL_LEAVE, UNPAID_LEAVE, COMP_TIME,
    SICK, MATERNITY, ADAPTED_WORK, TRAINING, OTHER
}

@Serializable
enum class AbsenceStatus { REQUESTED, APPROVED, REJECTED }

@Serializable
enum class ResponsibilityType {
    WEEK_COUNT, MONTH_COUNT, MAINTENANCE, ADMIN, KPI, HACCP, STOCK, HAVI,
    TRAINING, MEETING, OFFICE, INTERVIEW, CREW_PLANNING, CUSTOM
}

@Serializable
enum class RecurrenceType { WEEKLY, MONTHLY_DAY, MONTH_END, SPECIFIC_DATE }

@Serializable
enum class PersonMarkerType { PRESENT, OFFICE, TRAINING, MEETING, MAINTENANCE, ADMIN, OTHER }

@Serializable
data class Employee(
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val role: EmployeeRole = EmployeeRole.MANAGER,
    val contractedDaysPerWeek: Int = 5,
    val contractedHoursPerWeek: Double = 40.0,
    val canSetup: Boolean = true,
    val canDay: Boolean = true,
    val canMiddle: Boolean = true,
    val canClose: Boolean = true,
    val canKpi: Boolean = true,
    val maxShiftsPerWeek: Int = 5,
    val active: Boolean = true
)

@Serializable
data class ShiftTemplate(
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val kind: ShiftKind,
    val start: String,
    val end: String,
    val enabledWeekdays: Set<Int> = (1..7).toSet(),
    val autoGenerated: Boolean = false
) {
    fun startTime(): LocalTime = LocalTime.parse(start)
    fun endTime(): LocalTime = LocalTime.parse(end)
}

@Serializable
data class Availability(
    val employeeId: String,
    val date: String,
    val available: Boolean = true,
    val earliestStart: String? = null,
    val latestEnd: String? = null,
    val fixedShiftKind: ShiftKind? = null
)

@Serializable
data class WeeklyAvailability(
    val employeeId: String,
    val weekday: Int,
    val available: Boolean = true,
    val earliestStart: String? = null,
    val latestEnd: String? = null,
    val fixedShiftKind: ShiftKind? = null
)

@Serializable
data class Absence(
    val id: String = UUID.randomUUID().toString(),
    val employeeId: String,
    val startDate: String,
    val endDate: String,
    val type: AbsenceType,
    val status: AbsenceStatus = AbsenceStatus.APPROVED,
    val note: String = ""
) {
    fun includes(date: LocalDate): Boolean {
        val start = runCatching { LocalDate.parse(startDate) }.getOrNull() ?: return false
        val end = runCatching { LocalDate.parse(endDate) }.getOrNull() ?: return false
        return !date.isBefore(start) && !date.isAfter(end)
    }
}

@Serializable
data class ResponsibilityRule(
    val id: String = UUID.randomUUID().toString(),
    val employeeId: String,
    val type: ResponsibilityType,
    val recurrence: RecurrenceType = RecurrenceType.WEEKLY,
    val weekday: Int = 1,
    val monthDay: Int? = null,
    val date: String? = null,
    val label: String = "",
    val preferScheduled: Boolean = true,
    val active: Boolean = true
)

@Serializable
data class PersonDayMarker(
    val id: String = UUID.randomUUID().toString(),
    val employeeId: String,
    val date: String,
    val type: PersonMarkerType = PersonMarkerType.PRESENT,
    val note: String = ""
)

@Serializable
data class DayDemand(
    val date: String,
    val guestCount: Int? = null,
    val minimumManagers: Int = 0,
    val note: String = ""
)

@Serializable
data class DayPartDemand(
    val id: String = UUID.randomUUID().toString(),
    val date: String,
    val label: String,
    val start: String,
    val end: String,
    val minimumManagers: Int = 1,
    val guestCount: Int? = null,
    val note: String = ""
) {
    fun startTime(): LocalTime = LocalTime.parse(start)
    fun endTime(): LocalTime = LocalTime.parse(end)
}

@Serializable
data class OperatingHours(
    val weekday: Int,
    val open: String,
    val close: String,
    val closed: Boolean = false
) {
    fun openTime(): LocalTime = LocalTime.parse(open)
    fun closeTime(): LocalTime = LocalTime.parse(close)
    fun isTwentyFourHours(): Boolean = !closed && openTime() == closeTime()
}

@Serializable
data class ShiftSwapRecord(
    val id: String = UUID.randomUUID().toString(),
    val firstAssignmentId: String,
    val secondAssignmentId: String,
    val firstEmployeeId: String,
    val secondEmployeeId: String,
    val firstDate: String,
    val secondDate: String,
    val createdAt: String = java.time.LocalDateTime.now().toString()
)

@Serializable
data class DayNote(
    val date: String,
    val text: String
)

@Serializable
data class Assignment(
    val id: String = UUID.randomUUID().toString(),
    val employeeId: String,
    val date: String,
    val shiftTemplateId: String,
    val source: String = "generated"
)

@Serializable
data class PlannerSettings(
    val locationName: String = "Mijn restaurant",
    val maxConsecutiveWorkDays: Int = 6,
    val preferTwoConsecutiveDaysOff: Boolean = true,
    val busyWeekdays: Set<Int> = setOf(5, 6),
    val requireMiddleOnBusyDays: Boolean = true,
    val requireSetupDaily: Boolean = true,
    val requireCloseDaily: Boolean = true,
    val atwEnabled: Boolean = true,
    val strictDailyRestHours: Int = 11,
    val allowOneReducedDailyRestPer7Days: Boolean = false,
    val allowIncidentalTwelveHourNightShift: Boolean = false,
    val treatMaxConsecutiveDaysAsHardRule: Boolean = true,
    val traineeMustHaveExperiencedManager: Boolean = true,
    val minimizeBorrowedManagers: Boolean = true,
    val minimumTwoDayOffBlocks: Int = 1,
    val preferredTwoDayOffBlocks: Int = 2,
    val showWeeklyCount: Boolean = true,
    val weekCountWeekday: Int = 1,
    val showMonthCountOnLastDay: Boolean = true,
    val monthEndCloseManagers: Int = 2,
    val warnMinimumFreeSundays: Boolean = true,
    val autoGenerateSmartTemplates: Boolean = true,
    val autoFixAfterManualChanges: Boolean = false,
    val protectManualAssignmentsDuringAutoFix: Boolean = true
)

@Serializable
data class AppState(
    val year: Int = LocalDate.now().year,
    val month: Int = LocalDate.now().monthValue,
    val employees: List<Employee> = emptyList(),
    val shiftTemplates: List<ShiftTemplate> = defaultShiftTemplates(),
    val availability: List<Availability> = emptyList(),
    val weeklyAvailability: List<WeeklyAvailability> = emptyList(),
    val absences: List<Absence> = emptyList(),
    val responsibilities: List<ResponsibilityRule> = emptyList(),
    val personMarkers: List<PersonDayMarker> = emptyList(),
    val dayDemands: List<DayDemand> = emptyList(),
    val dayPartDemands: List<DayPartDemand> = emptyList(),
    val operatingHours: List<OperatingHours> = defaultOperatingHours(),
    val swapHistory: List<ShiftSwapRecord> = emptyList(),
    val dayNotes: List<DayNote> = emptyList(),
    val assignments: List<Assignment> = emptyList(),
    val assignmentHistory: List<Assignment> = emptyList(),
    val settings: PlannerSettings = PlannerSettings()
)

fun defaultShiftTemplates(): List<ShiftTemplate> = listOf(
    ShiftTemplate(name = "Setup", kind = ShiftKind.SETUP, start = "09:00", end = "17:00"),
    ShiftTemplate(name = "Setup HAVI", kind = ShiftKind.SETUP, start = "08:45", end = "16:45", enabledWeekdays = setOf(3, 5)),
    ShiftTemplate(name = "Dag", kind = ShiftKind.DAY, start = "09:00", end = "17:00"),
    ShiftTemplate(name = "Tussen", kind = ShiftKind.MIDDLE, start = "14:00", end = "22:00", enabledWeekdays = setOf(5, 6)),
    ShiftTemplate(name = "Sluit zo-do", kind = ShiftKind.CLOSE, start = "16:00", end = "00:00", enabledWeekdays = setOf(1, 2, 3, 4, 7)),
    ShiftTemplate(name = "Sluit vr-za", kind = ShiftKind.CLOSE, start = "17:00", end = "01:00", enabledWeekdays = setOf(5, 6)),
    ShiftTemplate(name = "KPI", kind = ShiftKind.KPI, start = "09:00", end = "17:00")
)

fun defaultOperatingHours(): List<OperatingHours> = (1..7).map { weekday ->
    OperatingHours(
        weekday = weekday,
        open = "08:00",
        close = if (weekday in setOf(5, 6)) "01:00" else "00:00"
    )
}

fun AppState.operatingHoursOn(date: LocalDate): OperatingHours? =
    operatingHours.lastOrNull { it.weekday == date.dayOfWeek.value }

fun AppState.isOpenOn(date: LocalDate): Boolean =
    operatingHoursOn(date)?.closed != true

fun AppState.allowsShiftOn(date: LocalDate, template: ShiftTemplate): Boolean {
    val hours = operatingHoursOn(date) ?: return true
    if (hours.closed) return false
    if (hours.isTwentyFourHours()) return true

    val anchor = LocalDate.of(2000, 1, 3)
    val opensAt = anchor.atTime(hours.openTime())
    var closesAt = anchor.atTime(hours.closeTime())
    if (!closesAt.isAfter(opensAt)) closesAt = closesAt.plusDays(1)

    val startsAt = anchor.atTime(template.startTime())
    var endsAt = anchor.atTime(template.endTime())
    if (!endsAt.isAfter(startsAt)) endsAt = endsAt.plusDays(1)

    return !startsAt.isBefore(opensAt) && !endsAt.isAfter(closesAt)
}

fun Employee.canWork(kind: ShiftKind): Boolean {
    if (role == EmployeeRole.HOST && kind in setOf(ShiftKind.SETUP, ShiftKind.CLOSE, ShiftKind.KPI)) {
        return false
    }
    return when (kind) {
        ShiftKind.SETUP -> canSetup
        ShiftKind.DAY -> canDay
        ShiftKind.MIDDLE -> canMiddle
        ShiftKind.CLOSE -> canClose
        ShiftKind.KPI -> canKpi
        ShiftKind.CUSTOM -> true
    }
}

fun EmployeeRole.countsAsManager(): Boolean = when (this) {
    EmployeeRole.MANAGER,
    EmployeeRole.RM,
    EmployeeRole.TRAINEE,
    EmployeeRole.BORROWED -> true
    EmployeeRole.HOST -> false
}

fun EmployeeRole.isExperiencedManager(): Boolean = when (this) {
    EmployeeRole.MANAGER,
    EmployeeRole.RM,
    EmployeeRole.BORROWED -> true
    EmployeeRole.TRAINEE,
    EmployeeRole.HOST -> false
}

fun Employee.countsAsManager(): Boolean = role.countsAsManager()
fun Employee.isExperiencedManager(): Boolean = role.isExperiencedManager()

fun Int.asDayOfWeek(): DayOfWeek = DayOfWeek.of(coerceIn(1, 7))
