package nl.roosterandroid.app

import java.time.Duration
import java.time.LocalDate
import java.time.LocalTime

/**
 * Bouwt alleen ontbrekende operationele templates. Handmatige templates blijven leidend.
 * Automatische templates worden bij elke run deterministisch opnieuw opgebouwd, behalve
 * wanneer ze nog in een huidig/historisch rooster worden gebruikt.
 */
object SmartShiftTemplates {
    fun augment(state: AppState): AppState {
        val referencedIds = (state.assignments + state.assignmentHistory)
            .map { it.shiftTemplateId }
            .toSet()

        val kept = state.shiftTemplates.filter { template ->
            !template.autoGenerated || template.id in referencedIds
        }.toMutableList()

        val base = state.copy(shiftTemplates = kept)
        val candidates = buildList {
            addAll(fromOperatingHours(base))
            addAll(fromAvailability(base))
        }
        val signatures = kept.map(::signature).toMutableSet()
        candidates.forEach { candidate ->
            if (signatures.add(signature(candidate))) kept += candidate
        }
        return base.copy(shiftTemplates = kept)
    }

    private fun fromAvailability(state: AppState): List<ShiftTemplate> {
        data class Window(val weekday: Int, val start: String, val end: String)

        val windows = buildList {
            state.weeklyAvailability
                .filter { it.available && it.earliestStart != null && it.latestEnd != null }
                .forEach { add(Window(it.weekday, it.earliestStart!!, it.latestEnd!!)) }

            state.availability
                .filter { it.available && it.earliestStart != null && it.latestEnd != null }
                .forEach { rule ->
                    val date = runCatching { LocalDate.parse(rule.date) }.getOrNull() ?: return@forEach
                    add(Window(date.dayOfWeek.value, rule.earliestStart!!, rule.latestEnd!!))
                }
        }

        return windows
            .filter { windowDurationMinutes(it.start, it.end) in 180..720 }
            .filterNot { window -> existingTemplateFits(state, window.weekday, window.start, window.end) }
            .groupBy { window ->
                val hours = state.operatingHours.lastOrNull { it.weekday == window.weekday }
                Triple(inferKind(window.start, window.end, hours), window.start, window.end)
            }
            .map { (key, grouped) ->
                val (kind, start, end) = key
                val weekdays = grouped.map { it.weekday }.toSet()
                ShiftTemplate(
                    id = stableId("availability", kind, start, end, weekdays),
                    name = "Flex $start-$end",
                    kind = kind,
                    start = start,
                    end = end,
                    enabledWeekdays = weekdays,
                    autoGenerated = true
                )
            }
    }

    private fun fromOperatingHours(state: AppState): List<ShiftTemplate> {
        val openRules = state.operatingHours.filterNot { it.closed }
        val output = mutableListOf<ShiftTemplate>()

        val allDayDays = openRules.filter { it.isTwentyFourHours() }.map { it.weekday }.toSet()
        if (allDayDays.isNotEmpty()) {
            output += auto("24h-night", "Nacht 00:00-08:00", ShiftKind.CUSTOM, "00:00", "08:00", allDayDays)
            output += auto("24h-day", "Dag 08:00-16:00", ShiftKind.DAY, "08:00", "16:00", allDayDays)
            output += auto("24h-evening", "Avond 16:00-00:00", ShiftKind.MIDDLE, "16:00", "00:00", allDayDays)
        }

        openRules.filterNot { it.isTwentyFourHours() }
            .groupBy { it.open to it.close }
            .forEach { (times, rules) ->
                val (openText, closeText) = times
                val weekdays = rules.map { it.weekday }.toSet()
                val open = LocalTime.parse(openText)
                val close = LocalTime.parse(closeText)
                val span = windowDurationMinutes(openText, closeText)

                if (span <= 480) {
                    val days = missingDaysForKind(state, ShiftKind.DAY, weekdays)
                    if (days.isNotEmpty()) {
                        output += auto("hours-day", "Dag $openText-$closeText", ShiftKind.DAY, openText, closeText, days)
                    }
                } else {
                    val setupEnd = open.plusHours(8).toString()
                    val closeStart = close.minusHours(8).toString()
                    val setupDays = missingDaysForKind(state, ShiftKind.SETUP, weekdays)
                    val closeDays = missingDaysForKind(state, ShiftKind.CLOSE, weekdays)

                    if (setupDays.isNotEmpty()) {
                        output += auto("hours-setup", "Setup $openText-$setupEnd", ShiftKind.SETUP, openText, setupEnd, setupDays)
                    }
                    if (closeDays.isNotEmpty()) {
                        output += auto("hours-close", "Sluit $closeStart-$closeText", ShiftKind.CLOSE, closeStart, closeText, closeDays)
                    }

                    if (span >= 720) {
                        val middleDays = missingDaysForKind(state, ShiftKind.MIDDLE, weekdays)
                        if (middleDays.isNotEmpty()) {
                            val midpoint = open.plusMinutes(span / 2)
                            val middleStart = midpoint.minusHours(4).toString()
                            val middleEnd = midpoint.plusHours(4).toString()
                            output += auto(
                                "hours-middle",
                                "Tussen $middleStart-$middleEnd",
                                ShiftKind.MIDDLE,
                                middleStart,
                                middleEnd,
                                middleDays
                            )
                        }
                    }
                }
            }

        return output
    }

    private fun missingDaysForKind(
        state: AppState,
        kind: ShiftKind,
        weekdays: Set<Int>
    ): Set<Int> = weekdays.filterNot { weekday ->
        state.shiftTemplates.any { template ->
            !template.autoGenerated && template.kind == kind && weekday in template.enabledWeekdays
        }
    }.toSet()

    private fun existingTemplateFits(
        state: AppState,
        weekday: Int,
        earliest: String,
        latest: String
    ): Boolean {
        val startLimit = LocalTime.parse(earliest)
        val endLimit = LocalTime.parse(latest)
        val anchor = LocalDate.of(2000, 1, 3)

        return state.shiftTemplates.any { template ->
            if (weekday !in template.enabledWeekdays) return@any false
            val start = anchor.atTime(template.startTime())
            var end = anchor.atTime(template.endTime())
            if (!end.isAfter(start)) end = end.plusDays(1)
            val earliestDt = anchor.atTime(startLimit)
            var latestDt = anchor.atTime(endLimit)
            if (!latestDt.isAfter(earliestDt)) latestDt = latestDt.plusDays(1)
            !start.isBefore(earliestDt) && !end.isAfter(latestDt)
        }
    }

    private fun inferKind(start: String, end: String, hours: OperatingHours?): ShiftKind {
        if (hours != null && !hours.closed && !hours.isTwentyFourHours()) {
            if (end == hours.close) return ShiftKind.CLOSE
            if (start == hours.open) return ShiftKind.SETUP
        }
        return if (LocalTime.parse(start).hour >= 13) ShiftKind.MIDDLE else ShiftKind.DAY
    }

    private fun auto(
        prefix: String,
        name: String,
        kind: ShiftKind,
        start: String,
        end: String,
        weekdays: Set<Int>
    ) = ShiftTemplate(
        id = stableId(prefix, kind, start, end, weekdays),
        name = name,
        kind = kind,
        start = start,
        end = end,
        enabledWeekdays = weekdays,
        autoGenerated = true
    )

    private fun stableId(
        prefix: String,
        kind: ShiftKind,
        start: String,
        end: String,
        weekdays: Set<Int>
    ): String = "auto-$prefix-${kind.name.lowercase()}-${start.replace(":", "")}-${end.replace(":", "")}-${weekdays.sorted().joinToString("")}"

    private fun signature(template: ShiftTemplate): String =
        "${template.kind}|${template.start}|${template.end}|${template.enabledWeekdays.sorted().joinToString(",")}"

    private fun windowDurationMinutes(start: String, end: String): Long {
        val a = LocalTime.parse(start)
        val b = LocalTime.parse(end)
        var minutes = Duration.between(a, b).toMinutes()
        if (minutes <= 0) minutes += 24 * 60
        return minutes
    }
}
