#!/usr/bin/env python3
from pathlib import Path
import re
import sys

ROOT = Path(sys.argv[1] if len(sys.argv) > 1 else '.').resolve()


def path(rel: str) -> Path:
    p = ROOT / rel
    if not p.exists():
        raise SystemExit(f'❌ Bestand ontbreekt: {rel}')
    return p


def read(rel: str) -> str:
    return path(rel).read_text(encoding='utf-8')


def write(rel: str, text: str) -> None:
    path(rel).write_text(text, encoding='utf-8')


def replace_required(text: str, old: str, new: str, label: str) -> str:
    if new in text:
        return text
    if old not in text:
        raise SystemExit(f'❌ Patchpunt niet gevonden: {label}')
    return text.replace(old, new, 1)


def matching_brace(text: str, open_idx: int) -> int:
    depth = 0
    i = open_idx
    mode = 'code'
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ''
        if mode == 'line':
            if ch == '\n': mode = 'code'
        elif mode == 'block':
            if ch == '*' and nxt == '/':
                mode = 'code'; i += 1
        elif mode == 'string':
            if ch == '\\': i += 1
            elif ch == '"': mode = 'code'
        elif mode == 'char':
            if ch == '\\': i += 1
            elif ch == "'": mode = 'code'
        else:
            if ch == '/' and nxt == '/': mode = 'line'; i += 1
            elif ch == '/' and nxt == '*': mode = 'block'; i += 1
            elif ch == '"': mode = 'string'
            elif ch == "'": mode = 'char'
            elif ch == '{': depth += 1
            elif ch == '}':
                depth -= 1
                if depth == 0: return i
        i += 1
    raise SystemExit('❌ Sluitende accolade niet gevonden')


def replace_function(text: str, signature_prefix: str, replacement: str, label: str) -> str:
    start = text.find(signature_prefix)
    if start < 0:
        if replacement.strip() in text:
            return text
        raise SystemExit(f'❌ Functie niet gevonden: {label}')
    open_idx = text.find('{', start)
    if open_idx < 0:
        raise SystemExit(f'❌ Openingsaccolade niet gevonden: {label}')
    end = matching_brace(text, open_idx)
    return text[:start] + replacement.rstrip() + text[end + 1:]


def function_block(text: str, signature_prefix: str):
    start = text.find(signature_prefix)
    if start < 0: raise SystemExit(f'❌ Functieblok niet gevonden: {signature_prefix}')
    open_idx = text.find('{', start)
    end = matching_brace(text, open_idx)
    return start, end + 1, text[start:end + 1]


def add_import(text: str, import_line: str) -> str:
    if import_line in text: return text
    matches = list(re.finditer(r'^import .+$', text, re.M))
    if not matches: raise SystemExit(f'❌ Geen imports gevonden voor {import_line}')
    pos = matches[-1].end()
    return text[:pos] + '\n' + import_line + text[pos:]


def insert_before_class_end(text: str, class_marker: str, code: str) -> str:
    if code.strip().splitlines()[0].strip() in text:
        return text
    cls = text.find(class_marker)
    if cls < 0 and class_marker.startswith('internal class '):
        cls = text.find(class_marker.replace('internal ', '', 1))
    if cls < 0: raise SystemExit(f'❌ Class marker niet gevonden: {class_marker}')
    open_idx = text.find('{', cls)
    end = matching_brace(text, open_idx)
    return text[:end] + '\n\n' + code.rstrip() + '\n' + text[end:]

# 1) Model: archiveer templates in plaats van hard verwijderen. Zo blijven oude roosters leesbaar.
rel = 'app/src/main/java/nl/roosterandroid/app/AppModels.kt'
s = read(rel)
s = replace_required(
    s,
    '    val enabledWeekdays: Set<Int> = (1..7).toSet(),\n    val autoGenerated: Boolean = false\n) {',
    '    val enabledWeekdays: Set<Int> = (1..7).toSet(),\n    val autoGenerated: Boolean = false,\n    val archived: Boolean = false\n) {',
    'ShiftTemplate archived veld'
)
write(rel, s)

# 2) Slimme templates: een bewust verwijderd auto-template blijft als tombstone bestaan en komt niet spontaan terug.
rel = 'app/src/main/java/nl/roosterandroid/app/SmartShiftTemplates.kt'
s = read(rel)
s = replace_required(
    s,
    '            !template.autoGenerated || template.id in referencedIds',
    '            template.archived || !template.autoGenerated || template.id in referencedIds',
    'archived auto-template bewaren'
)
old = '        return state.shiftTemplates.any { template ->\n            if (weekday !in template.enabledWeekdays) return@any false'
new = '        return state.shiftTemplates.any { template ->\n            if (template.archived) return@any false\n            if (weekday !in template.enabledWeekdays) return@any false'
s = replace_required(s, old, new, 'archived templates niet als actieve fit tellen')
write(rel, s)

# 3) ATW: alleen de aaneengesloten reeks rond de kandidaat mag een nieuwe maand blokkeren.
rel = 'app/src/main/java/nl/roosterandroid/app/AtwValidator.kt'
s = read(rel)
s = replace_required(
    s,
    '        val days = relevant.map { it.date }.distinct().sorted()\n        val streak = longestConsecutiveDayStreak(days)',
    '        val streak = consecutiveStreakIncluding(date, relevant)',
    'candidate-centered consecutive days'
)
helper = '''    private fun consecutiveStreakIncluding(date: LocalDate, shifts: List<ScheduledShift>): Int {
        val dates = shifts.map { it.date }.toSet()
        if (date !in dates) return 0
        var count = 1
        var cursor = date.minusDays(1)
        while (cursor in dates) {
            count++
            cursor = cursor.minusDays(1)
        }
        cursor = date.plusDays(1)
        while (cursor in dates) {
            count++
            cursor = cursor.plusDays(1)
        }
        return count
    }

'''
if 'private fun consecutiveStreakIncluding(' not in s:
    anchor = '    private fun longestConsecutiveDayStreak('
    idx = s.find(anchor)
    if idx < 0: raise SystemExit('❌ ATW helper-invoegpunt niet gevonden')
    s = s[:idx] + helper + s[idx:]
write(rel, s)

# 4) Solver: gearchiveerde templates niet meer plannen en historische ATW-fouten niet als nieuwe fout tellen.
rel = 'app/src/main/java/nl/roosterandroid/app/ScheduleEngine.kt'
s = read(rel)
start, end, block = function_block(s, '    private fun templatesForKind(')
if '.filter { !it.archived }' not in block:
    block = replace_required(
        block,
        '        return state.shiftTemplates\n            .filter {',
        '        return state.shiftTemplates\n            .filter { !it.archived }\n            .filter {',
        'templatesForKind archivefilter'
    )
s = s[:start] + block + s[end:]
start, end, block = function_block(s, '    private fun genericTemplates(')
if '!template.archived &&' not in block:
    block = replace_required(
        block,
        '                template.autoGenerated &&',
        '                !template.archived &&\n                template.autoGenerated &&',
        'automatic custom archivefilter'
    )
s = s[:start] + block + s[end:]

s = replace_required(
    s,
    '''        val finalState = state.copy(assignments = generated, assignmentHistory = history)
        val atwErrors = atw.validate(finalState).count {
            it.severity == AtwValidator.Severity.ERROR
        }''',
    '''        val atwErrors = introducedAtwErrors(state, generated, history).size''',
    'buildAttempt alleen nieuwe ATW-fouten'
)
s = replace_required(
    s,
    '''        val finalState = state.copy(assignments = assignments, assignmentHistory = history)
        val atwErrors = atw.validate(finalState).count {
            it.severity == AtwValidator.Severity.ERROR
        }''',
    '''        val atwErrors = introducedAtwErrors(state, assignments, history).size''',
    'evaluate alleen nieuwe ATW-fouten'
)
old_warn = '''        val finalState = state.copy(assignments = assignments, assignmentHistory = history)
        atw.validate(finalState)
            .filter { it.severity == AtwValidator.Severity.ERROR }
            .take(20)'''
new_warn = '''        introducedAtwErrors(state, assignments, history)
            .take(20)'''
if old_warn in s:
    s = s.replace(old_warn, new_warn, 1)

introduced_helper = '''    private fun introducedAtwErrors(
        state: AppState,
        assignments: List<Assignment>,
        history: List<Assignment>
    ): List<AtwValidator.Violation> {
        fun key(v: AtwValidator.Violation): String =
            "${v.employeeId}|${v.date}|${v.rule}|${v.message}"

        val baseline = atw.validate(
            state.copy(assignments = emptyList(), assignmentHistory = history)
        ).filter { it.severity == AtwValidator.Severity.ERROR }
            .map(::key)
            .toSet()

        return atw.validate(
            state.copy(assignments = assignments, assignmentHistory = history)
        ).filter { it.severity == AtwValidator.Severity.ERROR }
            .filter { key(it) !in baseline }
    }

'''
if 'private fun introducedAtwErrors(' not in s:
    idx = s.find('    private fun evaluate(')
    if idx < 0: raise SystemExit('❌ Solver ATW helper-invoegpunt niet gevonden')
    s = s[:idx] + introduced_helper + s[idx:]
write(rel, s)

# 5) Controller: veilig bewerken/verwijderen + custom dienst + baseline-diff bij handmatig wijzigen.
rel = 'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/DesktopController.kt'
s = read(rel)
update_fun = '''    fun updateTemplate(template: ShiftTemplate) {
        val current = state.shiftTemplates.firstOrNull { it.id == template.id }
        if (current == null) {
            addTemplate(template.copy(archived = false))
            return
        }
        val referenced = (state.assignments + state.assignmentHistory).any {
            it.shiftTemplateId == current.id
        }
        if (referenced) {
            val replacement = ShiftTemplate(
                name = template.name,
                kind = template.kind,
                start = template.start,
                end = template.end,
                enabledWeekdays = template.enabledWeekdays,
                autoGenerated = false,
                archived = false
            )
            val updated = state.shiftTemplates.map {
                if (it.id == current.id) it.copy(archived = true) else it
            } + replacement
            commitActive(state.copy(shiftTemplates = updated), "Diensttemplate aangepast • oude roosters blijven intact")
        } else {
            val updated = state.shiftTemplates.map {
                if (it.id == current.id) template.copy(autoGenerated = false, archived = false) else it
            }
            commitActive(state.copy(shiftTemplates = updated), "Diensttemplate aangepast")
        }
    }'''
s = replace_function(s, '    fun updateTemplate(template: ShiftTemplate)', update_fun, 'updateTemplate')

controller_methods = '''    fun removeTemplate(templateId: String) {
        val template = state.shiftTemplates.firstOrNull { it.id == templateId && !it.archived }
        if (template == null) {
            showStatus("Diensttemplate niet gevonden")
            return
        }
        val updated = state.shiftTemplates.map {
            if (it.id == templateId) it.copy(archived = true) else it
        }
        commitActive(state.copy(shiftTemplates = updated), "Diensttemplate verwijderd")
    }

    fun setManualCustomAssignment(
        employeeId: String,
        date: String,
        start: String,
        end: String,
        kind: ShiftKind
    ) {
        val parsed = runCatching { LocalDate.parse(date) }.getOrNull()
        if (parsed == null) {
            showStatus("Ongeldige datum")
            return
        }
        val existing = state.shiftTemplates.firstOrNull {
            !it.archived &&
                !it.autoGenerated &&
                it.kind == kind &&
                it.start == start &&
                it.end == end &&
                parsed.dayOfWeek.value in it.enabledWeekdays
        }
        val template = existing ?: ShiftTemplate(
            name = "Aangepast $start-$end",
            kind = kind,
            start = start,
            end = end,
            enabledWeekdays = setOf(parsed.dayOfWeek.value),
            autoGenerated = false,
            archived = false
        )
        if (existing == null) {
            commitActive(state.copy(shiftTemplates = state.shiftTemplates + template), "Aangepaste dienst toegevoegd")
        }
        setManualAssignment(employeeId, date, template.id)
    }
'''
if 'fun removeTemplate(templateId: String)' not in s:
    s = insert_before_class_end(s, 'class DesktopController', controller_methods)
elif 'template.copy(archived = true)' not in s:
    remove_template_fun = '''    fun removeTemplate(templateId: String) {
        val template = state.shiftTemplates.firstOrNull {
            it.id == templateId && !it.archived
        }
        if (template == null) {
            showStatus("Diensttemplate niet gevonden")
            return
        }
        val updated = state.shiftTemplates.map {
            if (it.id == templateId) it.copy(archived = true) else it
        }
        commitActive(
            state.copy(shiftTemplates = updated),
            "${template.name} verwijderd • oude roosters blijven intact"
        )
    }'''
    s = replace_function(
        s,
        '    fun removeTemplate(templateId: String)',
        remove_template_fun,
        'removeTemplate archive compatibility'
    )

manual_fun = '''    fun setManualAssignment(employeeId: String, date: String, templateId: String?) {
        val without = state.assignments.filterNot {
            it.employeeId == employeeId && it.date == date
        }
        if (templateId == null) {
            commitActive(state.copy(assignments = without), "Dienst op vrij gezet")
            return
        }

        val template = state.shiftTemplates.firstOrNull { it.id == templateId && !it.archived }
        if (template == null) {
            showStatus("Niet opgeslagen: diensttemplate is verwijderd")
            return
        }
        manualBlockReason(employeeId, date, templateId)?.let {
            showStatus("Niet opgeslagen: $it")
            return
        }

        val candidate = Assignment(
            employeeId = employeeId,
            date = date,
            shiftTemplateId = templateId,
            source = "manual"
        )
        val proposed = state.copy(assignments = without + candidate)
        val baselineKeys = validator.validate(state)
            .filter { it.severity == AtwValidator.Severity.ERROR && it.employeeId == employeeId }
            .map(::violationKey)
            .toSet()
        val newErrors = validator.validate(proposed)
            .filter { it.severity == AtwValidator.Severity.ERROR && it.employeeId == employeeId }
            .filter { violationKey(it) !in baselineKeys }

        if (newErrors.isNotEmpty()) {
            showStatus("Niet opgeslagen: ${newErrors.first().message}")
            return
        }
        commitActive(proposed, "Handmatige dienst opgeslagen")
    }'''
if 'fun setManualAssignment(employeeId: String, date: String, templateId: String?)' in s:
    s = replace_function(
        s,
        '    fun setManualAssignment(employeeId: String, date: String, templateId: String?)',
        manual_fun,
        'setManualAssignment'
    )
else:
    # Sommige desktop-baselines hebben deze API nog niet. Voeg hem dan toe
    # in plaats van de hele hotfix te laten stoppen.
    s = insert_before_class_end(s, 'class DesktopController', manual_fun)
write(rel, s)

# 6) RulesPanel: actieve templates tonen en echte edit/remove knoppen toevoegen.
rel = 'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/RulesPanel.kt'
s = read(rel)
s = add_import(s, 'import javax.swing.JOptionPane')
if 'controller.state.shiftTemplates.filterNot { it.archived }' not in s:
    s = replace_required(
        s,
        '        controller.state.shiftTemplates.forEach { template ->',
        '        controller.state.shiftTemplates.filterNot { it.archived }.forEach { template ->',
        'RulesPanel actieve templates'
    )
button_anchor = '''            add(primaryButton("Slimme templates voorstellen") {
                controller.refreshSmartTemplates()
            })'''
button_new = button_anchor + '''
            add(secondaryButton("Bewerken") { editTemplate() })
            add(secondaryButton("Verwijderen") { removeTemplate() })'''
s = replace_required(s, button_anchor, button_new, 'template edit/remove buttons')
methods = '''    private data class TemplateChoice(val template: ShiftTemplate) {
        override fun toString(): String = "${template.name}  ${template.start}-${template.end}"
    }

    private fun chooseTemplate(title: String): ShiftTemplate? {
        val options = controller.state.shiftTemplates
            .filterNot { it.archived }
            .map(::TemplateChoice)
            .toTypedArray()
        if (options.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Er zijn geen actieve diensttemplates.", title, JOptionPane.INFORMATION_MESSAGE)
            return null
        }
        return (JOptionPane.showInputDialog(
            this,
            "Kies een diensttemplate:",
            title,
            JOptionPane.PLAIN_MESSAGE,
            null,
            options,
            options.first()
        ) as? TemplateChoice)?.template
    }

    private fun editTemplate() {
        val selected = chooseTemplate("Diensttemplate bewerken") ?: return
        DesktopDialogs.template(this, selected)?.let(controller::updateTemplate)
    }

    private fun removeTemplate() {
        val selected = chooseTemplate("Diensttemplate verwijderen") ?: return
        val answer = JOptionPane.showConfirmDialog(
            this,
            "${selected.name} ${selected.start}-${selected.end} verwijderen?\\nBestaande oude roosters blijven hun oorspronkelijke tijden houden.",
            "Diensttemplate verwijderen",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        )
        if (answer == JOptionPane.YES_OPTION) controller.removeTemplate(selected.id)
    }
'''
if 'private fun chooseTemplate(title: String)' not in s:
    s = insert_before_class_end(s, 'class RulesPanel', methods)
write(rel, s)

# 7) SchedulePanel: expliciete handmatige diensteditor. Geen beschikbaarheid meer verwarren met de echte dienst.
rel = 'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/SchedulePanel.kt'
s = read(rel)
s = add_import(s, 'import java.awt.FlowLayout')
s = add_import(s, 'import javax.swing.JPanel')
if 'ManualScheduleEditor.open(' not in s:
    cls = s.find('class SchedulePanel')
    if cls < 0: raise SystemExit('❌ SchedulePanel class niet gevonden')
    init_idx = s.find('    init {', cls)
    if init_idx < 0: raise SystemExit('❌ SchedulePanel init niet gevonden')
    init_open = s.find('{', init_idx)
    init_end = matching_brace(s, init_open)
    addition = '''
        // v0.11.1: beschikbaarheid is alleen een venster; de echte dienst blijft apart wijzigbaar.
        run {
            val border = layout as? java.awt.BorderLayout
            val previousNorth = border?.getLayoutComponent(java.awt.BorderLayout.NORTH) as? Component
            if (previousNorth != null) remove(previousNorth)
            val wrapper = JPanel(java.awt.BorderLayout()).apply {
                if (previousNorth != null) add(previousNorth, java.awt.BorderLayout.CENTER)
                add(JPanel(FlowLayout(FlowLayout.LEFT, 8, 4)).apply {
                    add(secondaryButton("Dienst aanpassen") {
                        ManualScheduleEditor.open(this@SchedulePanel, controller)
                    })
                }, java.awt.BorderLayout.SOUTH)
            }
            add(wrapper, java.awt.BorderLayout.NORTH)
        }
'''
    # Component might need import; use fully qualified cast instead to avoid import.
    addition = addition.replace(' as? Component', ' as? java.awt.Component')
    s = s[:init_end] + addition + s[init_end:]
write(rel, s)

# 8) Voeg de nieuwe editor en regressietest toe.
editor_src = ROOT / '.v011/files/ManualScheduleEditor.kt'
test_src = ROOT / '.v011/files/V0111RegressionTest.kt'
if not editor_src.exists() or not test_src.exists():
    raise SystemExit('❌ v0.11.1 assets ontbreken')
(ROOT / 'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/ManualScheduleEditor.kt').write_text(editor_src.read_text(encoding='utf-8'), encoding='utf-8')
(ROOT / 'desktopApp/src/test/kotlin/nl/roosterandroid/desktop/V0111RegressionTest.kt').write_text(test_src.read_text(encoding='utf-8'), encoding='utf-8')

# 9) Versie zichtbaar maken.
rel = 'desktopApp/build.gradle.kts'
s = read(rel).replace('version = "0.11.0"', 'version = "0.11.1"')
write(rel, s)
rel = 'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/DesktopMain.kt'
s = read(rel)
s = s.replace('RoosterPlanner 0.11', 'RoosterPlanner 0.11.1').replace('v0.11', 'v0.11.1')
write(rel, s)

print('✅ RoosterPlanner v0.11.1 hotfix toegepast')
print('   • templates bewerken/verwijderen met historiebehoud')
print('   • handmatige dienst los van beschikbaarheidsvenster')
print('   • oude ATW-fout blokkeert volgende maand niet meer')
print('   • regressietests toegevoegd')
