#!/usr/bin/env python3
from pathlib import Path
import sys

root = Path(sys.argv[1] if len(sys.argv) > 1 else '.').resolve()
checks = {
    'app/src/main/java/nl/roosterandroid/app/AppModels.kt': [
        'val archived: Boolean = false',
        'enum class EmployeeRole { MANAGER, RM, TRAINEE, BORROWED, HOST }',
    ],
    'app/src/main/java/nl/roosterandroid/app/AtwValidator.kt': [
        'consecutiveStreakIncluding(date, relevant)',
        'private fun consecutiveStreakIncluding(',
    ],
    'app/src/main/java/nl/roosterandroid/app/ScheduleEngine.kt': [
        '.filter { !it.archived }',
        'private fun introducedAtwErrors(',
        'introducedAtwErrors(state, generated, history).size',
        'introducedAtwErrors(state, assignments, history).size',
    ],
    'app/src/main/java/nl/roosterandroid/app/SmartShiftTemplates.kt': [
        'template.archived || !template.autoGenerated',
        'if (template.archived) return@any false',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/DesktopController.kt': [
        'fun removeTemplate(templateId: String)',
        'fun setManualCustomAssignment(',
        'template.copy(archived = true)',
        'val baselineKeys = validator.validate(state)',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/RulesPanel.kt': [
        'secondaryButton("Bewerken")',
        'secondaryButton("Verwijderen")',
        'filterNot { it.archived }',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/SchedulePanel.kt': [
        'primaryButton("Dienst aanpassen")',
        'ManualScheduleEditor.open(',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/ManualScheduleEditor.kt': [
        'Beschikbaarheid blijft alleen het toegestane tijdvenster',
        'Aangepaste tijd...',
    ],
    'desktopApp/src/test/kotlin/nl/roosterandroid/desktop/V0111RegressionTest.kt': [
        'historicalConsecutiveDayErrorDoesNotPoisonNextMonth',
        'archivedAutoTemplateDoesNotComeBack',
        'editingReferencedTemplatePreservesOldShiftAndCreatesReplacement',
    ],
    'desktopApp/build.gradle.kts': ['version = "0.11.2"'],
}

errors = []
for rel, needles in checks.items():
    p = root / rel
    if not p.exists():
        errors.append(f'{rel}: bestand ontbreekt')
        continue
    text = p.read_text(encoding='utf-8')
    for needle in needles:
        if needle not in text:
            errors.append(f'{rel}: marker ontbreekt: {needle}')

model = (root / 'app/src/main/java/nl/roosterandroid/app/AppModels.kt').read_text(encoding='utf-8')
role_line = next((ln for ln in model.splitlines() if 'enum class EmployeeRole' in ln), '')
if 'CREW' in role_line:
    errors.append('AppModels.kt: CREW mag niet in EmployeeRole staan')

if errors:
    print('❌ v0.11.2 statische debug mislukt:')
    for err in errors:
        print(' -', err)
    raise SystemExit(1)

print('✅ v0.11.2 statische debug OK')
print('   model / archive / solver / ATW / templates / manual editor / regressietests aanwezig')
