#!/usr/bin/env python3
from pathlib import Path
import sys

root = Path(sys.argv[1] if len(sys.argv) > 1 else '.').resolve()
checks = {
    'app/src/main/java/nl/roosterandroid/app/AppModels.kt': [
        'val archived: Boolean = false',
        'enum class EmployeeRole { MANAGER, RM, TRAINEE, BORROWED, HOST }',
    ],
    'app/src/main/java/nl/roosterandroid/app/AtwValidator.kt': [
        'consecutiveStreakIncluding(',
        'private fun consecutiveStreakIncluding(',
    ],
    'app/src/main/java/nl/roosterandroid/app/ScheduleEngine.kt': [
        '.filter { !it.archived }',
        'private fun introducedAtwErrors(',
        'introducedAtwErrors(state, generated, history).size',
        'introducedAtwErrors(state, assignments, history).size',
    ],
    'app/src/main/java/nl/roosterandroid/app/SmartShiftTemplates.kt': [
        'template.archived || !template.autoGenerated',
        'if (template.archived) return@any false',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/DesktopController.kt': [
        'fun removeTemplate(templateId: String)',
        'fun setManualCustomAssignment(',
        'template.copy(archived = true)',
        'val baselineKeys = validator.validate(state)',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/RulesPanel.kt': [
        'secondaryButton("Bewerken")',
        'secondaryButton("Verwijderen")',
        'filterNot { it.archived }',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/SchedulePanel.kt': [
        'primaryButton("Dienst aanpassen")',
        'ManualScheduleEditor.open(',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/ManualScheduleEditor.kt': [
        'Beschikbaarheid blijft alleen het toegestane tijdvenster',
        'Aangepaste tijd...',
    ],
    'desktopApp/src/test/kotlin/nl/roosterandroid/desktop/V0111RegressionTest.kt': [
        'historicalConsecutiveDayErrorDoesNotPoisonNextMonth',
        'archivedAutoTemplateDoesNotComeBack',
        'editingReferencedTemplatePreservesOldShiftAndCreatesReplacement',
    ],
    'desktopApp/build.gradle.kts': ['version = "0.12.0-alpha3"'],
}


checks.update({
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/DesktopStorage.kt': [
        'lastLoadNotice',
        'newestValidBackup()',
        'roosterplanner-corrupt-',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/DesktopDialogs.kt': [
        'existing: Availability? = null',
        'existing: ResponsibilityRule? = null',
        'existing: PersonDayMarker? = null',
        'De contracturen passen niet binnen',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/RulesPanel.kt': [
        'strictDailyRestHours = strictRest.value as Int',
        'busyWeekdays = busyWeekdayChecks',
    ],
    'desktopApp/src/test/kotlin/nl/roosterandroid/desktop/V0111RegressionTest.kt': [
        'corruptedPrimaryStateRestoresBackup',
    ],
})


checks.update({
    'app/src/main/java/nl/roosterandroid/app/AppModels.kt': [
        'loanSourceLocationId',
        'loanSourceEmployeeId',
        'loanSourceLocationName',
    ],
    'app/src/main/java/nl/roosterandroid/app/ScheduleStorage.kt': [
        'rooster_state.backup.json',
        'preserveCorrupt(',
        'atomicWrite(',
    ],
    'app/build.gradle.kts': [
        'versionCode = 14',
        'versionName = "0.12.0-alpha3"',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/DesktopController.kt': [
        'borrowEmployeeFromLocation(',
        'it.isExperiencedManager()',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/TeamPanel.kt': [
        'Leenmanager uit vestiging',
        'loanSourceLocationName',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/DesktopWorkspace.kt': [
        'val schemaVersion: Int = 12',
    ],
})


checks.update({
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/DesktopController.kt': [
        'recordUndo: Boolean = true',
        'autoFix(recordUndo = false)',
        'if (recordUndo) {',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/DesktopDialogs.kt': [
        'fun applyRoleDefaults()',
        'EmployeeRole.HOST',
        'setup.isEnabled = !host',
    ],
    'desktopApp/src/test/kotlin/nl/roosterandroid/desktop/DesktopControllerTest.kt': [
        'manualEditAndAutoFixUseSingleUndoStep',
    ],
})


checks.update({
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/DesktopController.kt': [
        'allowOperationalOverride: Boolean = false',
        'fun manualOverrideWarnings(',
        'private fun hardManualBlockReason(',
        '"manual-override"',
        '"manual-custom-override"',
    ],
    'desktopApp/src/main/kotlin/nl/roosterandroid/desktop/ManualScheduleEditor.kt': [
        '"⚠ "',
        '"Handmatige override"',
        '"Toch plaatsen?"',
        'allowOperationalOverride =',
    ],
    'desktopApp/src/test/kotlin/nl/roosterandroid/desktop/DesktopControllerTest.kt': [
        'operationalManualOverrideRequiresExplicitConfirmation',
        'approvedAbsenceRemainsHardBlockDuringOverride',
    ],
})

errors = []
for rel, needles in checks.items():
    p = root / rel
    if not p.exists():
        errors.append(f'{rel}: bestand ontbreekt')
        continue
    text = p.read_text(encoding='utf-8')
    for needle in needles:
        if needle not in text:
            errors.append(f'{rel}: marker ontbreekt: {needle}')

model = (root / 'app/src/main/java/nl/roosterandroid/app/AppModels.kt').read_text(encoding='utf-8')
role_line = next((ln for ln in model.splitlines() if 'enum class EmployeeRole' in ln), '')
if 'CREW' in role_line:
    errors.append('AppModels.kt: CREW mag niet in EmployeeRole staan')

if errors:
    print('❌ v0.12 statische debug mislukt:')
    for err in errors:
        print(' -', err)
    raise SystemExit(1)

print('✅ v0.12 statische debug OK')
print('   model / archive / solver / ATW / templates / manual editor / regressietests aanwezig')
