package nl.roosterandroid.desktop

import nl.roosterandroid.app.AppState
import nl.roosterandroid.app.Assignment
import nl.roosterandroid.app.DayDemand
import nl.roosterandroid.app.Employee
import nl.roosterandroid.app.EmployeeRole
import nl.roosterandroid.app.PlannerSettings
import nl.roosterandroid.app.ScheduleEngine
import nl.roosterandroid.app.ShiftKind
import nl.roosterandroid.app.ShiftTemplate
import nl.roosterandroid.app.SmartShiftTemplates
import nl.roosterandroid.app.WeeklyAvailability
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.nio.file.Files

class V0111RegressionTest {
    @Test
    fun historicalConsecutiveDayErrorDoesNotPoisonNextMonth() {
        val employee = Employee(
            name = "Manager A",
            role = EmployeeRole.MANAGER,
            contractedDaysPerWeek = 0,
            contractedHoursPerWeek = 0.0,
            maxShiftsPerWeek = 7
        )
        val day = ShiftTemplate(id = "day", name = "Dag", kind = ShiftKind.DAY, start = "09:00", end = "17:00")
        val oldBrokenHistory = (1..7).map { dayOfMonth ->
            Assignment(
                employeeId = employee.id,
                date = "2026-07-${dayOfMonth.toString().padStart(2, '0')}",
                shiftTemplateId = day.id,
                source = "history-test"
            )
        }
        val state = AppState(
            year = 2026,
            month = 9,
            employees = listOf(employee),
            shiftTemplates = listOf(day),
            assignmentHistory = oldBrokenHistory,
            dayDemands = listOf(DayDemand(date = "2026-09-07", minimumManagers = 1)),
            settings = PlannerSettings(
                requireSetupDaily = false,
                requireCloseDaily = false,
                requireMiddleOnBusyDays = false,
                traineeMustHaveExperiencedManager = false,
                autoGenerateSmartTemplates = false,
                maxConsecutiveWorkDays = 6,
                treatMaxConsecutiveDaysAsHardRule = true,
                minimumTwoDayOffBlocks = 0,
                preferredTwoDayOffBlocks = 0,
                warnMinimumFreeSundays = false
            )
        )

        val result = ScheduleEngine().generate(state)
        assertTrue(
            "Een oude fout in juli mag september niet blokkeren",
            result.assignments.any { it.employeeId == employee.id && it.date == "2026-09-07" }
        )
    }

    @Test
    fun archivedAutoTemplateDoesNotComeBack() {
        val employee = Employee(
            name = "Flex",
            contractedDaysPerWeek = 0,
            contractedHoursPerWeek = 0.0
        )
        val removed = ShiftTemplate(
            id = "auto-flex-custom-1000-1800-1",
            name = "Flex 10:00-18:00",
            kind = ShiftKind.CUSTOM,
            start = "10:00",
            end = "18:00",
            enabledWeekdays = setOf(1),
            autoGenerated = true,
            archived = true
        )
        val state = AppState(
            year = 2026,
            month = 9,
            employees = listOf(employee),
            shiftTemplates = listOf(removed),
            weeklyAvailability = listOf(
                WeeklyAvailability(
                    employeeId = employee.id,
                    weekday = 1,
                    available = true,
                    earliestStart = "10:00",
                    latestEnd = "18:00"
                )
            )
        )

        val updated = SmartShiftTemplates.augment(state)
        assertTrue(updated.shiftTemplates.any { it.id == removed.id && it.archived })
        assertFalse(updated.shiftTemplates.any {
            !it.archived && it.start == "10:00" && it.end == "18:00" && it.kind == ShiftKind.CUSTOM
        })
    }

    @Test
    fun editingReferencedTemplatePreservesOldShiftAndCreatesReplacement() {
        val directory = Files.createTempDirectory("roosterplanner-v0111-template-")
        val employee = Employee(name = "A")
        val original = ShiftTemplate(id = "original", name = "Tussen", kind = ShiftKind.MIDDLE, start = "14:00", end = "22:00")
        val historical = Assignment(employeeId = employee.id, date = "2026-08-01", shiftTemplateId = original.id, source = "history")
        val state = AppState(
            year = 2026,
            month = 9,
            employees = listOf(employee),
            shiftTemplates = listOf(original),
            assignmentHistory = listOf(historical)
        )
        val storage = DesktopStorage(directory)
        storage.save(DesktopWorkspace.fromAppState(state))
        val controller = DesktopController(storage)

        controller.updateTemplate(original.copy(start = "13:00", end = "21:00"))

        val archivedOriginal = controller.state.shiftTemplates.firstOrNull { it.id == original.id }
        assertNotNull(archivedOriginal)
        assertTrue(archivedOriginal!!.archived)
        assertEquals("14:00", archivedOriginal.start)
        assertTrue(controller.state.shiftTemplates.any {
            !it.archived && it.id != original.id && it.start == "13:00" && it.end == "21:00"
        })
        assertEquals(original.id, controller.state.assignmentHistory.single().shiftTemplateId)
    }

    @Test
    fun removingTemplateArchivesInsteadOfBreakingHistory() {
        val directory = Files.createTempDirectory("roosterplanner-v0111-remove-")
        val employee = Employee(name = "A")
        val original = ShiftTemplate(id = "to-remove", name = "Dag", kind = ShiftKind.DAY, start = "09:00", end = "17:00")
        val assignment = Assignment(employeeId = employee.id, date = "2026-09-01", shiftTemplateId = original.id)
        val storage = DesktopStorage(directory)
        storage.save(DesktopWorkspace.fromAppState(AppState(
            year = 2026,
            month = 9,
            employees = listOf(employee),
            shiftTemplates = listOf(original),
            assignments = listOf(assignment)
        )))
        val controller = DesktopController(storage)

        controller.removeTemplate(original.id)

        assertTrue(controller.state.shiftTemplates.single { it.id == original.id }.archived)
        assertEquals(original.id, controller.state.assignments.single().shiftTemplateId)
    }
}
